/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/3D ROTULOS GABRIEL.gltf");
  return (
    <group {...props} dispose={null}>
      
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["TQ_ARD-geom"].geometry}
        material={materials["TQ_ARD_front"]}
      />
            <mesh
        castShadow
        receiveShadow
        geometry={nodes["TQ_ARD-geom"].geometry}
        material={materials["TQ_ARD_back"]}
      />
            <mesh
        castShadow
        receiveShadow
        geometry={nodes["TQ_ARD-geom"].geometry}
        material={materials["TQ_ARD_edge"]}
      />



 
    </group>
  );
}

useGLTF.preload("/3D ROTULOS GABRIEL.gltf");